[OPTIONS]
enable: 1

[RULES]
IN ACCEPT -p tcp -dport 22 -log info # SSH Access
IN ACCEPT -p tcp -dport 8006 -log info # GUI Management
IN DROP -p tcp -dport 23 # Block Telnet
IN DROP -p tcp -dport 445 # Block SMB from WAN

[group avs-admin]
IN ACCEPT -p tcp -dport 80 -source 10.0.5.0/24
IN ACCEPT -p tcp -dport 443 -source 10.0.5.0/24
